########################################
# 由于 GitHub API 限制，最多可以设置 60 个
########################################

links:
  # 我近期动态（20条记录）
  - https://api.github.com/repos/codepzj/blog/issues?per_page=20
